<?php

use Gedisa\LaravelSimpleHealthCheck\Tests\TestCase;
use Orchestra\Testbench\Concerns\WithWorkbench;

class HealthCheckControllerWithOutRedisTest extends TestCase
{
    use WithWorkbench;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_has_healthcheck_redis_failed()
    {
        $response = $this->get('/healthcheck');
        $response->assertStatus(503);

        $this->assertFalse($response->json()['redis']);
        $this->assertTrue($response->json()['database']);
        $this->assertTrue($response->json()['sentry']);
    }

    public function test_has_healthcheck_redis_and_db_failed()
    {
        config()->set('database.default', 'mysql');

        $response = $this->get('/healthcheck');
        $response->assertStatus(503);

        $this->assertFalse($response->json()['redis']);
        $this->assertFalse($response->json()['database']);
        $this->assertTrue($response->json()['sentry']);
    }

    public function test_has_healthcheck_redis_and_sentry_failed()
    {
        config()->set('database.redis.default.host', 'test');
        config()->set('sentry.dsn', 'test');

        $response = $this->get('/healthcheck');
        $response->assertStatus(503);

        $this->assertFalse($response->json()['redis']);
        $this->assertTrue($response->json()['database']);
        $this->assertFalse($response->json()['sentry']);
    }

    public function test_has_healthcheck_service_unavailable()
    {
        config()->set('database.redis.default.host', 'test');
        config()->set('database.default', 'mysql');
        config()->set('sentry.dsn', 'test');

        $response = $this->get('/healthcheck');
        $response->assertStatus(503);

        $this->assertFalse($response->json()['redis']);
        $this->assertFalse($response->json()['database']);
        $this->assertFalse($response->json()['sentry']);
    }
}
