<?php

use Gedisa\LaravelSimpleHealthCheck\Tests\FailedTestCase;
use Orchestra\Testbench\Concerns\WithWorkbench;

class HealthCheckControllerFailedTest extends FailedTestCase
{
    use WithWorkbench;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_has_healthcheck_internal_error()
    {
        config()->set('database.redis', null);
        config()->set('database.default', false);
        config()->set('sentry.dsn', 'http://localhost');

        $response = $this->get('/healthcheck');
        $response->assertStatus(500);
    }
}
