<?php

use Gedisa\LaravelSimpleHealthCheck\Tests\RedisTestCase;
use Orchestra\Testbench\Concerns\WithWorkbench;

class HealthCheckControllerWithRedisTest extends RedisTestCase
{
    use WithWorkbench;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_healthcheck_all_ok()
    {
        $response = $this->get('/healthcheck');

        $response->assertStatus(200);
        $this->assertTrue($response->json()['redis']);
        $this->assertTrue($response->json()['database']);
        $this->assertTrue($response->json()['sentry']);
    }

    public function test_has_healthcheck_db_failed()
    {
        config()->set('database.default', 'mysql');

        $response = $this->get('/healthcheck');
        $response->assertStatus(503);

        $this->assertTrue($response->json()['redis']);
        $this->assertFalse($response->json()['database']);
        $this->assertTrue($response->json()['sentry']);
    }

    public function test_has_healthcheck_sentry_failed()
    {
        config()->set('sentry.dsn', 'test');

        $response = $this->get('/healthcheck');
        $response->assertStatus(503);

        $this->assertTrue($response->json()['redis']);
        $this->assertTrue($response->json()['database']);
        $this->assertFalse($response->json()['sentry']);
    }

    public function test_has_healthcheck_db_and_sentry_failed()
    {
        config()->set('database.default', 'mysql');
        config()->set('sentry.dsn', 'test');

        $response = $this->get('/healthcheck');
        $response->assertStatus(503);

        $this->assertTrue($response->json()['redis']);
        $this->assertFalse($response->json()['database']);
        $this->assertFalse($response->json()['sentry']);
    }
}
